theme: jekyll-theme-cayman
title: Learn German Today
description: Simple steps to perfect German
github:
  page2:  page2.html
  page3:  page3.html
  page4:  page4.html
  page5:  page5.html
  page6:  practice.html
  page7:  practice2.html
