theme: jekyll-theme-cayman
title: gerWOmany
description: A simple overview of Germany with an emphasis on women-related topics  
github:
  page2:  About-Germany.html
  page3:  Women-In-History.html
  page4:  Fashion.html
  page5:  Immigration.html
  page6:  Feminism.html
